### PR TITLE
Implement Bark Blocks

### LINKED ISSUE #41: Bark Blocks
These are blocks that move indefinitely in one direction until hitting a wall or block when the player speaks/barks nearby.

<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>

<sub><sub>also called Michael's Mechanic</sub></sub>

### PR DESCRIPTION
**Pull request by BlockCrusader**
Implements Bark Blocks; closes #41  

NOTICE: There is a minor issue where the player can disrupt (e.g. slow to a near-stop) Bark Block movement by getting in the way. The block will return to full speed as soon as the player gets out of the way, though. Not entirely sure what the desired behavior for this scenario should be. May be subject to further improvements before merging, or a new Issue of its own; your call.

### CODE REVIEW

**Comment by BlockCrusader** [comment]
I had initially tried implementing detection through the speak aura but couldn't figure it out, hence the stun function workaround. That said, I can still try again at making the former approach work, since it'd be cleaner.

**Comment by MistOfJudgement** [comment]
I was messing around with having the speak aura on a layer and allowing objects that are barked at to detect the aura instead of the inverse. Maybe thats an option

**Comment by BlockCrusader** [comment]
> I was messing around with having the speak aura on a layer and allowing objects that are barked at to detect the aura instead of the inverse. Maybe thats an option

I like the idea of having a collision layer for objects that can be barked at, that should be possible seeing as there are plenty of layers available (Usually the UI shows 16 total, but there could be more). 
Instead of having objects detect the bark (Which would require repeated collision detection boilerplate code), the aura's existing detection for enemies could be extended to also detect objects on this 'bark' layer. Likewise, objects that can be barked at could have a `on_barked` function that the aura calls on-collision, similar to how the aura calls `damage` and `stun` functions on enemies it touches.

**Comment by BlockCrusader** [comment]
I noticed there are also 'bark interactables', #42 . If the aforementioned approach is implemented, it would be best if both Bark Blocks and the interactables (As well as any other non-enemy objects that interact with the bark) conformed to that system. 
In light of bark interactables being their own Issue, I think it might be best we go ahead and merge Bark Blocks as-is, and then make a follow-up Issue for implementing a bark collision layer for use by both Blocks and interactables.

**Comment by Justin1L8** [comment]
The only issue with using the stun function is that it isn't actually "stunning" it, and that it requires it to be on the enemy layer. I wouldn't suggest the bark block do the detection. We can just rename the function, and either remove the check that its an enemy or replace it with something more general (e.g. a "Stunnable" group?)

**Comment by BlockCrusader** [comment]
Implemented changes previously discussed; there is now a new 'Barkable' collision layer (layer 9) for use by any entities that can be interacted with via. the bark. An entity must have layer 9 active to be hit by the Bark (Whereas before, entities in the enemy layer (3) were hit). The 'stun' function has been renamed to 'barked' to match this change.

Only the Bark Blocks have been adjusted to utilize layer 9 for Bark collision; other entities - namely enemies - still need to be tweaked.

**Pull request merged**
